services:
  db:
    image: postgres:16
    container_name: scrapescout-db
    environment:
      POSTGRES_USER: scrape
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: scrapedb
    volumes:
      - scrapescout_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scrape -d scrapedb"]
      interval: 5s
      retries: 5
    ports: ["5432:5432"]

  app:
    build: .
    container_name: scrapescout-app
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]

volumes:
  scrapescout_pgdata:
