"""Added date_populated column to Job table

Revision ID: 579ef285cdcb
Revises: 4593d48ade15
Create Date: 2025-04-25 23:37:43.270793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579ef285cdcb'
down_revision = '4593d48ade15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_populated', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('date_populated')

    # ### end Alembic commands ###
