"""add category column to job

Revision ID: 8fd8a3fb6720
Revises: 29e30b587b67
Create Date: 2024-03-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd8a3fb6720'
down_revision = '29e30b587b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_job_category', 'category', ['category'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint('fk_job_category', type_='foreignkey')
        batch_op.drop_column(sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ### 