"""empty message

Revision ID: f871a77d5d28
Revises: a885c3836a4e
Create Date: 2025-04-24 19:48:50.887780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f871a77d5d28'
down_revision = 'a885c3836a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('favorite')
        batch_op.drop_column('email')
        batch_op.drop_column('salary')

    # ### end Alembic commands ###
