name: 🕒 Scheduled Job Indexer

on:
  workflow_dispatch:
  schedule:
    # every 5 minutes
    - cron: '0 0 * * *'   # 04:00 local = 00:00 UTC
    - cron: '0 4 * * *'   # 08:00 local = 04:00 UTC
    - cron: '0 8 * * *'   # 12:00 local = 08:00 UTC
    - cron: '0 12 * * *'  # 16:00 local = 12:00 UTC
    - cron: '0 16 * * *'  # 20:00 local = 16:00 UTC
    - cron: '0 20 * * *'  # 00:00 local (next day) = 20:00 UTC

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run index_all_jobs
        env:
          FLASK_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python - <<EOF
          import sys, os
          sys.path.insert(0, os.path.abspath(os.getcwd()))

          from run import app
          from application.scrape import index_all_jobs

          with app.app_context():
              index_all_jobs()
          EOF
